########################### NETWORKS
# You may customize the network subnets (192.168.x.0/24) below as you please.
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  
########################### SECRETS
  
include:
  ########################### SERVICES
  # HOSTNAME defined in .env file

  # CORE
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/wireguard.yml
  # MAINTENANCE
  - compose/$HOSTNAME/ddns-updater.yml
  - compose/$HOSTNAME/watchtower.yml