services:
  # AdGuard Home - DNS AdBlocking
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: unless-stopped
    profiles: ["core", "all", "dns"]
    networks:
      - t3_proxy    
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      # - 68:68/udp
      - 8182:80/tcp
      - 8183:443/tcp
      - 8183:443/udp
      # - 3000:3000/tcp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 6060:6060/tcp
    volumes:
      - $DOCKERDIR/appdata/adguardhome/conf:/opt/adguardhome/conf
      - $DOCKERDIR/appdata/adguardhome/work:/opt/adguardhome/work
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.adguardhome-rtr.entrypoints=websecure"
      - "traefik.http.routers.adguardhome-rtr.rule=Host(`adguardhome.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.adguardhome-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.adguardhome-rtr.service=adguardhome-svc"
      - "traefik.http.services.adguardhome-svc.loadbalancer.server.port=80"
      # Enable Watchtower Monitoring
      - "com.centurylinklabs.watchtower.monitor-only=true"