http:
  middlewares:
    chain-authelia:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-https-redirectscheme
          - middlewares-redirect-www-to-non-www
          - middlewares-authelia
          # - middlewares-compress
