services:
  # WireGuard - Secure VPN Tunnel
  wireguard:
    # image: lscr.io/linuxserver/wireguard:latest
    image: local/wireguard-iptables:latest
    build:
      context: $DOCKERDIR/custom/wireguard
      dockerfile: $DOCKERDIR/custom/wireguard/Dockerfile-wireguard
    container_name: wireguard
    restart: unless-stopped
    profiles: ["core", "all"]
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - default
    ports:
      - 51820:51820/udp
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - $DOCKERDIR/appdata/wireguard:/config
      - /lib/modules:/lib/modules #optional
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      PEERS: silentmedia
      PERSISTENTKEEPALIVE_PEERS: all
    labels:
      # Enable Watchtower Monitoring
      - "com.centurylinklabs.watchtower.monitor-only=true"