services:
  # Bazarr - Subtitle Management
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "arrs", "all"]
    # ports:
    #   - "6767:6767"
    volumes:
      - $DOCKERDIR/appdata/bazarr:/config
      - $MEDIADIR/Movies:/movies
      - "$MEDIADIR/TV Shows:/tv shows"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth
      - "traefik.http.routers.bazarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.bazarr-rtr.rule=Host(`bazarr.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.bazarr-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.bazarr-rtr.service=bazarr-svc"
      - "traefik.http.services.bazarr-svc.loadbalancer.server.port=6767"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
