services:
  # cross-seed - Fully-automatic cross-seeding
  cross-seed:
    container_name: cross-seed
    image: ghcr.io/cross-seed/cross-seed:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "downloads"]
    depends_on:
      - qbittorrent
      - prowlarr
    command: daemon
    volumes:
      - $DOCKERDIR/appdata/cross-seed:/config
      - $MEDIASERVERDIR:/mediaserver
    user: 1000:1000
    labels:
      # Enable WUD
      - "wud.watch=true"
      - "wud.tag.include=^latest$$"
