services:
  # Deemix - Deezer Music Downloader
  deemix:
    container_name: deemix
    image: ghcr.io/bambanah/deemix:latest
    network_mode: "service:gluetun-deemix"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "downloads"]
    # ports:
      # - "6595:6595" # Explosed via gluetun
    volumes:
      - $DOCKERDIR/appdata/deemix/config:/config
      - $DOCKERDIR/appdata/deemix/deemix-gui:/deemix-gui/config
      - $DOCKERDIR/appdata/deemix/downloads:/downloads # Requires /downloads to be mapped
      - $MEDIASERVERDIR:/mediaserver
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 0022
      DEEMIX_MUSIC_DIR: /mediaserver/downloads/deemix
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "wget --no-verbose --tries=1 --spider https://example.com || exit 1"
      interval: 3m
      timeout: 10s
      retries: 1
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
