services:
  # DeUnhealth - Restart your unhealthy containers safely (e.g. containers depending on VPN and VPN reconnects)
  deunhealth:
    container_name: deunhealth
    image: qmcgaw/deunhealth:latest
    networks:
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "maintenance", "all"]    
    depends_on:
      - socket-proxy
    environment:
      LOG_LEVEL: info
      HEALTH_SERVER_ADDRESS: 127.0.0.1:9999
      TZ: $TZ
      DOCKER_HOST: tcp://socket-proxy:2375
    labels:
      # Enable WUD
      - "wud.watch=true"
      - "wud.tag.include=^latest$$"