services:
  # FlareSolverr - Bypass Cloudflare and DDoS-GUARD
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "arrs", "all"]
    networks:
      - t3_proxy
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"