services:
  # Gluetun - VPN Client for Docker Containers
  gluetun-slskd:
    container_name: gluetun-slskd
    image: qmcgaw/gluetun:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    profiles: ["all", "apps", "downloads", "vpn"]
    # ports:
      # - "6595:6595" # Exposing Deemix through Docker Host LAN IP
      # - "5030:5030" # Exposing slskd through Docker Host LAN IP
      # - "8998:17442" # Exposing YoutubeDL-Material through Docker Host LAN IP
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/appdata/gluetun-slskd:/gluetun
    environment:
      TZ: $TZ
      UPDATER_PERIOD: 2h
      # Wireguard
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $SLSKD_WIREGUARD_PRIVATE_KEY
      SERVER_CITIES: $SLSKD_WIREGUARD_SERVER_CITIES
      VPN_PORT_FORWARDING: on
      PORT_FORWARD_ONLY: on
      # https://github.com/qdm12/gluetun/issues/2154
      DNS_ADDRESS: 9.9.9.9
      DOT: off
      HEALTH_TARGET_ADDRESS: cloudflare.com:80
      HEALTH_VPN_DURATION_INITIAL: 120s
      WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: 25s
    labels:
      - "traefik.enable=true"
      ## Deemix labels
        # HTTP Routers
      - "traefik.http.routers.deemix-rtr.entrypoints=websecure"
      - "traefik.http.routers.deemix-rtr.rule=Host(`deemix.$DOMAINNAME`)"
        # Middlewares
      - "traefik.http.routers.deemix-rtr.middlewares=chain-authelia@file"
        # HTTP Services
      - "traefik.http.routers.deemix-rtr.service=deemix-svc"
      - "traefik.http.services.deemix-svc.loadbalancer.server.port=6595"
      ## slskd labels
        # HTTP Routers
      - "traefik.http.routers.slskd-rtr.entrypoints=websecure"
      - "traefik.http.routers.slskd-rtr.rule=Host(`slskd.$DOMAINNAME`)"
        # Middlewares
      - "traefik.http.routers.slskd-rtr.middlewares=chain-authelia@file"
        # HTTP Services
      - "traefik.http.routers.slskd-rtr.service=slskd-svc"
      - "traefik.http.services.slskd-svc.loadbalancer.server.port=5030"
      ## YoutubeDL-Material labels
        # HTTP Routers
      - "traefik.http.routers.ytdl-material-rtr.entrypoints=websecure"
      - "traefik.http.routers.ytdl-material-rtr.rule=Host(`ytdl-material.$DOMAINNAME`)"
        # Middlewares
      - "traefik.http.routers.ytdl-material-rtr.middlewares=chain-authelia-nosniffdisabled@file"
        # HTTP Services
      - "traefik.http.routers.ytdl-material-rtr.service=ytdl-material-svc"
      - "traefik.http.services.ytdl-material-svc.loadbalancer.server.port=17442"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.monitor-only=true"
