services:
  # glueforward - Updates slskd's listening port to Gluetun's forwarded port
  glueforward-slskd:
    container_name: glueforward-slskd
    # image: ghcr.io/geoffreycoulaud/glueforward:latest # Official image
    image: local/glueforward-curl:latest # Add curl to official image
    build:
      dockerfile: $DOCKERDIR/custom/Dockerfile-glueforward
    network_mode: "service:gluetun-slskd"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "downloads", "vpn"]
    depends_on:
      - gluetun-slskd
      - slskd
    environment:
      SERVICE_TYPE: 'slskd'
      GLUETUN_URL: 'http://localhost:8000'
      GLUETUN_API_KEY: $GLUETUN_SLSKD_API_KEY
      SLSKD_URL: 'http://localhost:5030'
      SLSKD_USERNAME: $SLSKD_USERNAME
      SLSKD_PASSWORD: $SLSKD_PASSWORD
      SUCCESS_INTERVAL: 60
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 1m
      timeout: 10s
      retries: 1
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
