services:
  # glueslskd - Updates slskd's listening port to Gluetun's forwarded port
  glueslskd:
    container_name: glueslskd
    # image: ghcr.io/geoffreycoulaud/glueslskd:latest
    # image: local/glueslskd:latest
    image: glueslskd
    network_mode: "service:gluetun-deemix"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "downloads", "vpn"]
    depends_on:
      - gluetun-deemix
      - slskd
    volumes:
      - $DOCKERDIR/appdata/slskd/slskd.yml:/config/slskd.yml
    environment:
      GLUETUN_URL: 'http://localhost:8000'
      SLSKD_CONFIG_PATH: "/config/slskd.yml"
      SUCCESS_INTERVAL: 60
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "curl -sf https://example.com || exit 1"
      interval: 3m
      timeout: 10s
      retries: 1
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
