services:
  # Gluetun - VPN Client for Docker Containers and More
  # Gluetun only for use by torrent clients + on demand lan devices.
  # Arr apps do not need VPN (not recommended), unless you have ISP/country restrictions.
  gluetun-qbittorrent:
    container_name: gluetun-qbittorrent
    image: qmcgaw/gluetun:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    profiles: ["all", "apps", "downloads", "vpn"]
    ports:
      - "8081:8080" # Exposing qBittorrent through Docker Host LAN IP
    #   - 8888:8888/tcp # HTTP proxy
    #   - 8388:8388/tcp # Shadowsocks
    #   - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/appdata/gluetun-qbittorrent:/gluetun-qbittorrent
    environment:
      TZ: $TZ
      UPDATER_PERIOD: 24h
      # Wireguard
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $QBITTORRENT_WIREGUARD_PRIVATE_KEY
      SERVER_CITIES: $QBITTORRENT_WIREGUARD_SERVER_CITIES
      VPN_PORT_FORWARDING: on
      PORT_FORWARD_ONLY: on
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "wget --no-verbose --tries=1 --spider https://example.com || exit 1"
      interval: 3m
      timeout: 10s
      retries: 1
    labels:
      - "traefik.enable=true"
      ## qBittorrent labels
        # HTTP Routers
      - "traefik.http.routers.gluetun-qbittorrent-rtr.entrypoints=websecure"
      - "traefik.http.routers.gluetun-qbittorrent-rtr.rule=Host(`qbittorrent.$DOMAINNAME`)"
        # Middlewares
      - "traefik.http.routers.gluetun-qbittorrent-rtr.middlewares=chain-authelia@file"
        # HTTP Services
      - "traefik.http.routers.gluetun-qbittorrent-rtr.service=gluetun-svc"
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8080"
      # Enable Watchtower Monitoring
      - "com.centurylinklabs.watchtower.monitor-only=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
