services:
  # glueforward - Updates qBittorrent's listening port to Gluetun's forwarded port
  glueforward:
    container_name: glueforward
    # image: ghcr.io/geoffreycoulaud/glueforward:latest # Official image
    image: local/glueforward-curl:latest # Add curl to official image
    build:
      dockerfile: $DOCKERDIR/custom/Dockerfile-glueforward
    network_mode: "service:gluetun-qbittorrent"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "downloads", "vpn"]
    environment:
      SERVICE_TYPE: 'qbittorrent'
      GLUETUN_URL: 'http://localhost:8000'
      GLUETUN_API_KEY: $GLUETUN_QBITTORRENT_API_KEY
      QBITTORRENT_URL: 'http://localhost:8080'
      QBITTORRENT_USERNAME: $QBITTORRENT_USERNAME
      QBITTORRENT_PASSWORD: $QBITTORRENT_PASSWORD
      SUCCESS_INTERVAL: 60
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 1m
      timeout: 10s
      retries: 1
    labels:
      # # Enable WUD
      # - "wud.watch=true"
      # - "wud.tag.include=^latest$$"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
