services:
  # glueforward - Updates slskd's listening port to Gluetun's forwarded port
  glueforward-slskd:
    container_name: glueforward-slskd
    # image: ghcr.io/geoffreycoulaud/glueforward:latest # Official image

    # image: local/glueforward-curl:latest # Add curl to official image
    # build:
    #   dockerfile: $DOCKERDIR/custom/Dockerfile-glueforward

    build:
      context: ../../../repos/glueforward # Build from local repo
    
    pull_policy: build
    network_mode: "service:gluetun-slskd"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "downloads", "vpn"]
    depends_on:
      - gluetun-slskd
      - slskd
    environment:
      SERVICE_TYPE: 'slskd'
      GLUETUN_URL: 'http://localhost:8000'
      GLUETUN_API_KEY: $GLUETUN_SLSKD_API_KEY
      # SLSKD_URL: 'http://localhost:5030'
      SLSKD_API_KEY: $SLSKD_GLUEFORWARD_API_KEY
      SUCCESS_INTERVAL: 60
      SLSKD_CONFIG_PATH: "/config/slskd.yml"
    volumes:
      - $DOCKERDIR/appdata/slskd/slskd.yml:/config/slskd.yml
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
