services:
  # Gluetun - VPN Client for Docker Containers
  gluetun-qbittorrent:
    container_name: gluetun-qbittorrent
    image: qmcgaw/gluetun:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    profiles: ["all", "apps", "downloads", "vpn"]
    ports:
      - "8081:8080" # Exposing qBittorrent through Docker Host LAN IP
    #   - 8888:8888/tcp # HTTP proxy
    #   - 8388:8388/tcp # Shadowsocks
    #   - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/appdata/gluetun-qbittorrent:/gluetun
    environment:
      TZ: $TZ
      UPDATER_PERIOD: 2h
      # Wireguard
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $QBITTORRENT_WIREGUARD_PRIVATE_KEY
      SERVER_CITIES: $QBITTORRENT_WIREGUARD_SERVER_CITIES
      VPN_PORT_FORWARDING: on
      PORT_FORWARD_ONLY: on
      # https://github.com/qdm12/gluetun/issues/2154
      DNS_ADDRESS: 9.9.9.9
      DOT: off
      HEALTH_TARGET_ADDRESS: cloudflare.com:80
      HEALTH_VPN_DURATION_INITIAL: 120s
      WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: 25s
    labels:
      - "traefik.enable=true"
      ## qBittorrent labels
        # HTTP Routers
      - "traefik.http.routers.gluetun-qbittorrent-rtr.entrypoints=websecure"
      - "traefik.http.routers.gluetun-qbittorrent-rtr.rule=Host(`qbittorrent.$DOMAINNAME`)"
        # Middlewares
      - "traefik.http.routers.gluetun-qbittorrent-rtr.middlewares=chain-authelia@file"
        # HTTP Services
      - "traefik.http.routers.gluetun-qbittorrent-rtr.service=gluetun-svc"
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8080"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.monitor-only=true"
