services:
  # Gluetun - VPN Client for Docker Containers
  gluetun-qbittorrent:
    container_name: gluetun-qbittorrent
    image: qmcgaw/gluetun:latest
    networks:
      - t3_proxy
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    profiles: ["all", "apps", "downloads", "vpn"]
    ports:
      - "8081:8080" # Exposing qBittorrent through Docker Host LAN IP
    #   - 8888:8888/tcp # HTTP proxy
    #   - 8388:8388/tcp # Shadowsocks
    #   - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/appdata/gluetun-qbittorrent:/gluetun
    environment:
      TZ: $TZ
      UPDATER_PERIOD: 24h
      # Wireguard
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $QBITTORRENT_WIREGUARD_PRIVATE_KEY
      SERVER_CITIES: $QBITTORRENT_WIREGUARD_SERVER_CITIES
      VPN_PORT_FORWARDING: on
      PORT_FORWARD_ONLY: on
    labels:
      - "traefik.enable=true"
      ## qBittorrent labels
        # HTTP Routers
      - "traefik.http.routers.gluetun-qbittorrent-rtr.entrypoints=websecure"
      - "traefik.http.routers.gluetun-qbittorrent-rtr.rule=Host(`qbittorrent.$DOMAINNAME`)"
        # Middlewares
      - "traefik.http.routers.gluetun-qbittorrent-rtr.middlewares=chain-authelia@file"
        # HTTP Services
      - "traefik.http.routers.gluetun-qbittorrent-rtr.service=gluetun-svc"
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8080"
      # Enable Watchtower Monitoring
      - "com.centurylinklabs.watchtower.monitor-only=true"
