services:
  # Gluetun - VPN Client for Docker Containers and More
  # Gluetun only for use by torrent clients + on demand lan devices.
  # Arr apps do not need VPN (not recommended), unless you have ISP/country restrictions.
  gluetun-deemix:
    container_name: gluetun-deemix
    image: qmcgaw/gluetun:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    profiles: ["apps", "downloads", "vpn", "all"]
    # ports:
      # - "6595:6595" # Exposing Deemix through Docker Host LAN IP
      # - "5030:5030" # Exposing slskd through Docker Host LAN IP
      # - "8998:17442" # Exposing YoutubeDL-Material through Docker Host LAN IP
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/appdata/gluetun-deemix:/gluetun-deemix
    environment:
      TZ: $TZ
      UPDATER_PERIOD: 24h
      # Wireguard
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $DEEMIX_WIREGUARD_PRIVATE_KEY
      SERVER_CITIES: $DEEMIX_WIREGUARD_SERVER_CITIES
      VPN_PORT_FORWARDING: on
      PORT_FORWARD_ONLY: on
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "wget --no-verbose --tries=1 --spider https://example.com || exit 1"
      interval: 3m
      timeout: 10s
      retries: 1
    labels:
      - "traefik.enable=true"
      ## Deemix labels
        # HTTP Routers
      - "traefik.http.routers.deemix-rtr.entrypoints=websecure"
      - "traefik.http.routers.deemix-rtr.rule=Host(`deemix.$DOMAINNAME`)"
        # Middlewares
      - "traefik.http.routers.deemix-rtr.middlewares=chain-authelia@file"
        # HTTP Services
      - "traefik.http.routers.deemix-rtr.service=deemix-svc"
      - "traefik.http.services.deemix-svc.loadbalancer.server.port=6595"
      ## slskd labels
      #   # HTTP Routers
      # - "traefik.http.routers.slskd-rtr.entrypoints=websecure"
      # - "traefik.http.routers.slskd-rtr.rule=Host(`slskd.$DOMAINNAME`)"
      #   # Middlewares
      # - "traefik.http.routers.slskd-rtr.middlewares=chain-authelia@file"
      #   # HTTP Services
      # - "traefik.http.routers.slskd-rtr.service=slskd-svc"
      # - "traefik.http.services.slskd-svc.loadbalancer.server.port=5030"
      ## YoutubeDL-Material labels
        # HTTP Routers
      - "traefik.http.routers.ytdl-material-rtr.entrypoints=websecure"
      - "traefik.http.routers.ytdl-material-rtr.rule=Host(`ytdl-material.$DOMAINNAME`)"
        # Middlewares
      - "traefik.http.routers.ytdl-material-rtr.middlewares=chain-authelia-nosniffdisabled@file"
        # HTTP Services
      - "traefik.http.routers.ytdl-material-rtr.service=ytdl-material-svc"
      - "traefik.http.services.ytdl-material-svc.loadbalancer.server.port=17442"
      # Enable Watchtower Monitoring
      - "com.centurylinklabs.watchtower.monitor-only=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
