services:
  # Grafana - Graphical data visualization for InfluxDB data
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "monitoring", "all"]
    # ports:
      # - "3000:3000"
    user: "$PUID:$PGID"
    volumes:
      - $DOCKERDIR/appdata/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.grafana-rtr.entrypoints=websecure"
      - "traefik.http.routers.grafana-rtr.rule=Host(`grafana.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.grafana-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.grafana-rtr.service=grafana-svc"
      - "traefik.http.services.grafana-svc.loadbalancer.server.port=3000"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
