services:
  # Guacamole - Remote desktop, SSH, on Telnet on any HTML5 Browser
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "admin", "apps"]
    depends_on:
      - guacd
      - mariadb-guac
    # ports:
      # - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: $MARIADB_HOST
      MYSQL_PORT: 3306
      MYSQL_DATABASE_FILE: /run/secrets/guac_db_name
      MYSQL_USER_FILE: /run/secrets/guac_mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/guac_mysql_password
    secrets:
      - guac_db_name
      - guac_mysql_user
      - guac_mysql_password
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.guacamole-rtr.entrypoints=websecure"
      - "traefik.http.routers.guacamole-rtr.rule=Host(`guacamole.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.guacamole-rtr.middlewares=chain-authelia@file,add-guacamole"
      - "traefik.http.middlewares.add-guacamole.addPrefix.prefix=/guacamole"
      # HTTP Services
      - "traefik.http.routers.guacamole-rtr.service=guacamole-svc"
      - "traefik.http.services.guacamole-svc.loadbalancer.server.port=8080"
      # Enable WUD Monitoring
      - "wud.watch=true"
      - "wud.tag.include=^latest$$"
      - "wud.trigger.exclude=docker.autoupdate"

  # Guacamole Daemon - Needed for Guacamole
  guacd:
    container_name: guacd
    image: guacamole/guacd:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "admin", "apps"]
    labels:
      # Enable WUD Monitoring
      - "wud.watch=true"
      - "wud.tag.include=^latest$$"
      - "wud.trigger.exclude=docker.autoupdate"
