services:
   # Homepage - Application Dashboard
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    networks:
      - t3_proxy
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    # ports:
    #  - "$HOMEPAGE_PORT:3000" 
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
      - $APPDATADIR/homepage/images:/app/public/images
      - $APPDATADIR/homepage/icons:/app/public/icons
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_ALLOWED_HOSTS: $DOMAINNAME
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.rule=Host(`$DOMAINNAME`) || Host(`www.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.homepage-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
