services:
  # Jellyfin - Media Server
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "media"]
    ports:
      - "8096:8096"
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $TEMPDATADIR/jellyfin/cache:/cache
      - $TEMPDATADIR/jellyfin/metadata:/config/metadata
      - $MEDIADIR/Movies:/movies:ro
      - "$MEDIADIR/TV Shows:/tv:ro"
      - $MEDIADIR/Music:/music:ro
      - $MEDIADIR/Anime:/anime:ro
      # - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    user: $PUID:$PGID
    environment:
      UMASK_SET: 022
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.jellyfin-rtr.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.jellyfin-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "993"
