services:
  # Kavita - Manga Server
  kavita-manga:
    container_name: kavita-manga
    image: jvmilazz0/kavita:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "media"]
    ports:
      - "5000:5000"
    volumes:
      - $DOCKERDIR/appdata/kavita-manga:/kavita-manga/config
      - $TEMPDATADIR/kavita-manga/cache:/kavita-manga/config/cache
      - $TEMPDATADIR/kavita-manga/covers:/kavita-manga/config/covers
      - $TEMPDATADIR/kavita-manga/temp:/kavita-manga/config/temp
      - $MEDIADIR/Manga:/manga:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.kavita-manga-rtr.entrypoints=websecure"
      - "traefik.http.routers.kavita-manga-rtr.rule=Host(`kavita-manga.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.kavita-manga-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.kavita-manga-rtr.service=kavita-manga-svc"
      - "traefik.http.services.kavita-manga-svc.loadbalancer.server.port=5000"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
