services:
  # Lidarr - Music Management
  lidarr:
    container_name: lidarr
    # image: image: ghcr.io/hotio/lidarr:nightly
    image: local/lidarr-ffmpeg:latest # Add curl to official image
    build:
      dockerfile: $DOCKERDIR/custom/Dockerfile-lidarr
      pull: true
    pull_policy: build
    network_mode: "service:gluetun-slskd"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "arrs"]
    # ports:
    #   - "8686:8686" # Exposed via gluetun
    volumes:
      - $DOCKERDIR/appdata/lidarr:/config
      - $TEMPDATADIR/lidarr/MediaCover:/config/MediaCover
      - $MEDIASERVERDIR:/mediaserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 1m
      timeout: 10s
      retries: 1
    labels:
      # Enable WUD
      - "wud.watch=true"
      - "wud.tag.include=^pr-plugins$$"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
