services:
  # MKVToolNix - Video Editing (Remuxing - changing media container while keeping original source quality)
  mkvtoolnix:
    container_name: mkvtoolnix
    image: jlesage/mkvtoolnix:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "files", "all"]
    # ports:
    #   - "5800:5800"
    volumes:
      - $DOCKERDIR/appdata/mkvtoolnix:/config
      - $APPDATADIR/mkvtoolnix:/storage
      - $DOWNLOADSDIR:/downloads:ro
      - $APPDATADIR/docker-ripper:/docker-ripper:ro
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      UMASK: 002
      TZ: $TZ
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      VNC_PASSWORD: $MKVTOOLNIX_VNC_PASSWD
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.mkvtoolnix-rtr.entrypoints=websecure"
      - "traefik.http.routers.mkvtoolnix-rtr.rule=Host(`mkvtoolnix.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.mkvtoolnix-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.mkvtoolnix-rtr.service=mkvtoolnix-svc"
      - "traefik.http.services.mkvtoolnix-svc.loadbalancer.server.port=5800"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
