services:      
  # MongoDB - NoSQL Database for YoutubeDL-Material
  mongodb-ytdl:
    container_name: mongodb-ytdl
    image: mongo:4
    logging:
      driver: "none"
    network_mode: "service:gluetun-deemix"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["dbs", "all"]
    volumes:
      - $DOCKERDIR/appdata/mongodb-ytdl/config:/data/configdb
      - $DOCKERDIR/appdata/mongodb-ytdl/db:/data/db
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
