services:      
  # MongoDB - NoSQL Database for YoutubeDL-Material
  mongodb-ytdl:
    container_name: mongodb-ytdl
    image: mongo:4
    logging:
      driver: "none"
    network_mode: "service:gluetun-slskd"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "dbs", "downloads"]
    volumes:
      - $DOCKERDIR/appdata/mongodb-ytdl/config:/data/configdb
      - $DOCKERDIR/appdata/mongodb-ytdl/db:/data/db
    labels:
      # Enable WUD
      - "wud.watch=true"
      - "wud.tag.include=^4$$"
