services:
  # Plex - Media Server
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    security_opt:
      - no-new-privileges:true
    networks:
      - t3_proxy
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "33400:33400/tcp"
    restart: unless-stopped
    profiles: ["media", "all"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - $DOCKERDIR/appdata/plex:/config
      - $TEMPDATADIR/plex/transcode:/transcode
      - "$TEMPDATADIR/plex/metadata:/config/Library/Application Support/Plex Media Server/Metadata"
      - "$TEMPDATADIR/plex/media:/config/Library/Application Support/Plex Media Server/Media"
      - $MEDIADIR/Movies:/movies:ro
      - "$MEDIADIR/TV Shows:/tv:ro"
      - $MEDIADIR/Music:/music:ro
      - $MEDIADIR/Anime:/anime:ro
      # - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.plex-rtr.entrypoints=websecure"
      - "traefik.http.routers.plex-rtr.rule=Host(`plex.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.plex-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      TZ: $TZ
      PLEX_CLAIM_FILE: /run/secrets/plex_claim
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: "http://$SERVER_IP:32400/,https://plex.$DOMAINNAME/"
      ALLOWED_NETWORKS: $LOCAL_IPS
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
    secrets:
      - plex_claim