services:
  # Prowlarr - Torrent proxy
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "arrs"]
    # ports:
      # - "9696:9696"
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.prowlarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr-rtr.rule=Host(`prowlarr.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.prowlarr-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.prowlarr-rtr.service=prowlarr-svc"
      - "traefik.http.services.prowlarr-svc.loadbalancer.server.port=9696"
      # Enable WUD
      - "wud.watch=true"
      - "wud.tag.include=^latest$$"
