services:
  # qBittorrent - Torrent downloader
  qbittorrent:
    container_name: qbittorrent
    # image: lscr.io/linuxserver/qbittorrent:latest
    image: lscr.io/linuxserver/qbittorrent:5.1.2 # Static image for qbit_manage compatibility
    network_mode: "service:gluetun-qbittorrent"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "downloads"]
    # ports:
    #   - "8081:8080" # Explosed via gluetun
    volumes:
      - $DOCKERDIR/appdata/qbittorrent:/config
      - $MEDIASERVERDIR:/mediaserver
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 002
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels: # Traefik labels added via gluetun
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
