services:
  # qBit Manage - Manage qBittorrent Instance
  qbit_manage:
    container_name: qbit_manage
    image: ghcr.io/stuffanthings/qbit_manage:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "downloads", "all"]
    volumes:
      - $DOCKERDIR/appdata/qbit_manage:/config
      - $MEDIASERVERDIR:/mediaserver
      - $DOCKERDIR/appdata/qbittorrent/qBittorrent:/qbittorrent/:ro
    environment:
      - QBT_RUN=false
      - QBT_SCHEDULE=10
      - QBT_CONFIG=config.yml
      - QBT_LOGFILE=activity.log
      - QBT_CROSS_SEED=false
      - QBT_RECHECK=false
      - QBT_CAT_UPDATE=false
      - QBT_TAG_UPDATE=false
      - QBT_REM_UNREGISTERED=false
      - QBT_REM_ORPHANED=false
      - QBT_TAG_TRACKER_ERROR=false
      - QBT_TAG_NOHARDLINKS=false
      - QBT_SHARE_LIMITS=false
      - QBT_SKIP_CLEANUP=false
      - QBT_DRY_RUN=false
      - QBT_LOG_LEVEL=INFO
      - QBT_DIVIDER==
      - QBT_WIDTH=100
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
