services:
  # Readarr - Book management
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "arrs"]
    ports:
      - "8787:8787"
    volumes:
      - $DOCKERDIR/appdata/readarr:/config
      - $TEMPDATADIR/readarr/MediaCover:/config/MediaCover
      - $MEDIASERVERDIR:/mediaserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.readarr-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.readarr-rtr-bypass.rule=Host(`readarr.$DOMAINNAME`) && (Header(`X-Api-Key`, `$READARR_API_KEY`) || Query(`apikey`, `$READARR_API_KEY`))"
      - "traefik.http.routers.readarr-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.readarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.readarr-rtr.rule=Host(`readarr.$DOMAINNAME`)"
      - "traefik.http.routers.readarr-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.readarr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.readarr-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.readarr-rtr.service=readarr-svc"
      - "traefik.http.routers.readarr-rtr-bypass.service=readarr-svc"
      - "traefik.http.services.readarr-svc.loadbalancer.server.port=8787"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
