services:
  # slskd - Client-Server Application for Soulseek
  slskd:
    container_name: slskd
    image: slskd/slskd:latest
    network_mode: "service:gluetun-deemix"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "downloads"]
    # ports:
      # - "5030:5030" # Explosed via gluetun
    volumes:
     - $DOCKERDIR/appdata/slskd:/app
     - $DOWNLOADSDIR/slskd:/downloads/slskd
     - $MEDIADIR/Music:/music:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      SLSKD_USERNAME: $SLSKD_USERNAME
      SLSKD_PASSWORD: $SLSKD_PASSWORD
      SLSKD_SLSK_USERNAME: $SOULSEEK_USERNAME
      SLSKD_SLSK_PASSWORD: $SOULSEEK_PASSWORD
      # SLSKD_SHARED_DIR: '/music'
      SLSKD_DOWNLOADS_DIR: '/downloads/slskd/downloads'
      SLSKD_INCOMPLETE_DIR: '/downloads/slskd/incomplete'
      SLSKD_REMOTE_CONFIGURATION: false
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "wget --no-verbose --tries=1 --spider https://example.com || exit 1"
      interval: 3m
      timeout: 10s
      retries: 1
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"
