services:
  # sonarr-tagger - Automatically manage Sonarr movie tags based on custom format scores 
  sonarr-tagger:
    container_name: sonarr-tagger
    image: digimotong/sonarr-tagger:latest
    # image: local/sonarr-tagger:latest # Local image
    # build:
    #   context: ../../../repos/sonarr-tagger # Build from local repo
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps", "arrs", "dev"]
    environment:
      SONARR_URL: http://sonarr:8989
      SONARR_API_KEY: $SONARR_API_KEY
      LOG_LEVEL: INFO #DEBUG, INFO, WARNING, ERROR
      SCORE_THRESHOLD: 100
      INTERVAL_MINUTES: 20
      TAG_4K: true
      TAG_MIXED_RELEASE_GROUPS: true
      TAG_MOTONG: true
      MONITOR_EXISTING_SPECIALS: true
    labels:
      # Enable WUD
      - "wud.watch=true"
      - "wud.tag.include=^latest$$"
