services:
  # tdarr - Distributed Transcoding System
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - 8265:8265 # webUI port
    #   - 8266:8266 # server port
    restart: unless-stopped
    profiles: ["apps", "arrs", "files", "all"]
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "993"
    volumes:
      - $DOCKERDIR/appdata/tdarr/server:/app/server
      - $DOCKERDIR/appdata/tdarr/configs:/app/configs
      - $DOCKERDIR/appdata/tdarr/logs:/app/logs
      - $TEMPDATADIR/tdarr:/temp
      - $MEDIADIR/Movies:/movies:ro
      - "$MEDIADIR/TV Shows:/tv:ro"
      - $MEDIADIR/Anime:/anime:ro
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      serverIP: 0.0.0.0
      serverPort: 8266
      webUIPort: 8265
      auth: true
      internalNode: true
      inContainer: true
      ffmpegVersion: 6
      nodeName: 'Internal Node'
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.tdarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.tdarr-rtr.rule=Host(`tdarr.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.tdarr-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.tdarr-rtr.service=tdarr-svc"
      - "traefik.http.services.tdarr-svc.loadbalancer.server.port=8265"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
