services:
  # TeamSpeak 6 - Voice Communication Server
  teamspeak-server:
    container_name: teamspeak-server
    image: teamspeaksystems/teamspeak6-server:latest
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "apps"]
    # ports:
    #   - "9987:9987/udp"   # Default voice port
    #   - "30033:30033/tcp" # File transfer port
    #   - "10080:10080/tcp" # WebQuery port
    #   - "10022:10022/tcp" # SSHQuery port
    volumes:
      - $DOCKERDIR/appdata/teamspeak-server:/var/tsserver
    user: $PUID:$PGID
    environment:
      TZ: $TZ
      TSSERVER_LICENSE_ACCEPTED: accept
      TSSERVER_DEFAULT_PORT: 9987
      TSSERVER_VOICE_IP: 0.0.0.0
      TSSERVER_FILE_TRANSFER_PORT: 30033
      TSSERVER_FILE_TRANSFER_IP: 0.0.0.0
      TSSERVER_QUERY_HTTP_ENABLED: true
      TSSERVER_QUERY_HTTP_PORT: 10080
    labels:
      - "traefik.enable=true"
      # Voice
      - "traefik.udp.routers.teamspeak-voice.entrypoints=teamspeak-voice"
      - "traefik.udp.routers.teamspeak-voice.service=teamspeak-voice-svc"
      - "traefik.udp.services.teamspeak-voice-svc.loadbalancer.server.port=9987"
      # File Transfer
      - "traefik.tcp.routers.teamspeak-data.entrypoints=teamspeak-data"
      - "traefik.tcp.routers.teamspeak-data.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.teamspeak-data.service=teamspeak-data-svc"
      - "traefik.tcp.services.teamspeak-data-svc.loadbalancer.server.port=30033"
      # SSHQuery
      - "traefik.tcp.routers.teamspeak-squery.entrypoints=teamspeak-squery"
      - "traefik.tcp.routers.teamspeak-squery.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.teamspeak-squery.service=teamspeak-squery-svc"
      - "traefik.tcp.services.teamspeak-squery-svc.loadbalancer.server.port=10022"
      # Enable WUD
      - "wud.watch=true"
      - "wud.tag.include=^latest$$"

