services:
  # Tunarr - IPTV backed by Plex/Jellyfin
  tunarr:
    container_name: tunarr
    image: chrisbenincasa/tunarr:latest-vaapi
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - "8000:8000"
    restart: unless-stopped
    profiles: ["all", "apps", "media", "arrs"]
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "993"
    volumes:
      - $DOCKERDIR/appdata/tunarr:/config/tunarr
      - $TEMPDATADIR/tunarr/cache:/config/tunarr/cache
      - $TEMPDATADIR/tunarr/images:/config/tunarr/images
    environment:
      TZ: $TZ
      LOG_LEVEL: INFO
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.tunarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.tunarr-rtr.rule=Host(`tunarr.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.tunarr-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.tunarr-rtr.service=tunarr-svc"
      - "traefik.http.services.tunarr-svc.loadbalancer.server.port=8000"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
