services:
  # Tunarr - IPTV backed by Plex/Jellyfin
  tunarr:
    image: chrisbenincasa/tunarr:latest-nvidia
    container_name: tunarr
    security_opt:
      - no-new-privileges:true
    networks:
      - t3_proxy
    ports:
      - "8000:8000"
    restart: unless-stopped
    profiles: ["apps", "media", "arrs", "all"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - $DOCKERDIR/appdata/tunarr:/config/tunarr
      - $TEMPDATADIR/tunarr/cache:/config/tunarr/cache
      - $TEMPDATADIR/tunarr/images:/config/tunarr/images
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.tunarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.tunarr-rtr.rule=Host(`tunarr.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.tunarr-rtr.middlewares=chain-double-auth@file"
      # HTTP Services
      - "traefik.http.routers.tunarr-rtr.service=tunarr-svc"
      - "traefik.http.services.tunarr-svc.loadbalancer.server.port=8000"
      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      TZ: $TZ
      LOG_LEVEL: INFO