services:
  # WatchTower - Automatic Docker Container Updates
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "maintenance", "all"]
    networks:
      - socket_proxy
    depends_on:
      - socket-proxy
    environment:
      TZ: $TZ
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_SCHEDULE: "0 0 4 * * *" # Everyday at 04:00
      # WATCHTOWER_RUN_ONCE: true # Run once immediately
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: $WATCHTOWER_NOTIFICATION_URL
      DOCKER_HOST: tcp://socket-proxy:2375
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"