services:
  # YoutubeDL-Material - Material Design Frontend for youtube-dl
  ytdl-material:
    image: tzahi12345/youtubedl-material:latest
    container_name: ytdl-material
    depends_on:
      - mongodb-ytdl
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "downloads", "all"]
    network_mode: "service:gluetun-deemix"
    # ports:
      # - "8998:17442" # Explosed via gluetun
    volumes:
      - $DOCKERDIR/appdata/ytdl-material:/app/appdata
      - $DOWNLOADSDIR/ytdl-material/audio:/app/audio
      - $DOWNLOADSDIR/ytdl-material/video:/app/video
      - $DOWNLOADSDIR/ytdl-material/subscriptions:/app/subscriptions
      - $DOWNLOADSDIR/ytdl-material/users:/app/users
    environment: 
      UID: $PUID
      GID: $PGID
      ytdl_mongodb_connection_string: 'mongodb://localhost:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "curl -sf https://example.com || exit 1"
      interval: 3m
      timeout: 10s
      retries: 1
    labels:
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
      # Enable DeUnhealth
      - "deunhealth.restart.on.unhealthy=true"